lucky_numbers = [4, 8, 15, 16, 23, 42]
friends = ["Kevin", "Karen", "Jim", "Jim", "Oscar", "Toby"]
friends.append("Matthias")
lucky_numbers.append(50)
##friends.extend(lucky_numbers)
##friends.pop()
##friends.clear()
##friends.insert(1, "Kelly")
##friends.remove("Jim")
##friends.sort()
##print(friends.index("Oscar"))
##print(friends.count("Jim"))
##lucky_numbers.reverse()
##friends2 = friends.copy()
print(friends2)